### ISSUE TITLE
Maintainership of pygeobuf

### ISSUE THREAD

**Issue by sgillies** [pygeobuf/pygeobuf#36]
The pygeobuf project began as a prototype. Today https://github.com/mapbox/geobuf is the reference implementation of the geobuf encoding and Mapbox currently has no users of pygeobuf. We (Mapbox) would like to transfer the pygeobuf project to developers interested in actively maintaining it and making releases to the Python package index.

In https://github.com/mapbox/pygeobuf/pull/35 I proposed to transfer pygeobuf to the mysidewalk org, but I had overlooked the earlier offer by @jlaine in https://github.com/mapbox/pygeobuf/pull/32#issuecomment-289269789. My apologies for that oversight, @jlaine.

@jlaine @jguthmiller: can I ask the two of you to discuss joint maintainership (here or in other channels) and where you'd like to do it?

**Comment by jguthmiller** [comment]
@jlaine It's totally fine with me for your org to take ownership of the repo. You've been contributing longer, and we are already running off of our own fork. Either way, we definitely still want to help maintain the project.

**Comment by jlaine** [comment]
@jguthmiller I definitely don't think a single maintainer is the right way forward, I think the more the merrier. Do you know if there is a python-gis-related organisation we can talk onto, or should we just create a "pygeobuf" org?

**Comment by jlaine** [comment]
A quick look around did not yield any promising organisations so I created "pygeobuf", you should have received an invite

**Comment by jlaine** [comment]
Hi @sgillies as the organisation is now setup, (with Jake, you and me as admins) could you transfer the repo over to to the "pygeobuf" org?

**Comment by sgillies** [comment]
@jlaine @jguthmiller I will do. Can you each register usernames on Pypi if you haven't already and drop them in here? I'll add roles for you in the pygeobuf package.

**Comment by jlaine** [comment]
My pypi username is "sharky"

**Comment by jguthmiller** [comment]
mine is `jguthmiller`

**Comment by sgillies** [comment]
Sorry about the delay! https://github.com/pygeobuf/pygeobuf has arrived.
