### ISSUE TITLE
pip install pygeobuf?

### ISSUE THREAD

**Issue by SeaDude** [pygeobuf/pygeobuf#43]
My apologies if I'm missing something dead obvious, but I didn't see how to install the `pygeobuf` module anywhere in the README. 

**Trying `!pip install pygeobuf` resulted in:**

```
ERROR: Could not find a version that satisfies the requirement pygeobuf (from versions: none)
ERROR: No matching distribution found for pygeobuf
WARNING: You are using pip version 19.3.1; however, version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Could you advise me?
Thank you

**Comment by scw** [comment]
Try `pip install geobuf` which should pick up the 1.1.1 release.

**Comment by SeaDude** [comment]
I submitted a pull request for the `README.md` file here. Please federate to the Mapbox README and the PyPi `Usage` area. 
Thanks!
