### ISSUE TITLE
Using argument dim > 2 during encoding implies weird output during the decoding

### ISSUE THREAD

**Issue by GPoloVera** [pygeobuf/pygeobuf#48]
If you use the **dim** argument of the **Encoder.encode** method and then decodes, the output contains again just 2 dimensions but with more points at the end with weird values. This problem appear in the **version 1.1.1**

Quick example:
`import geojson`
`import geobuf`
`l = [(1,2,3),(4,5,6)]`
`geobuf.decode(geobuf.encode(geojson.LineString(l),6,3))`

The output of this encode - decode is:

`OrderedDict([('type', 'LineString'),
             ('coordinates', [[1.0, 2.0], [4.0, 5.0], [7.0, 8.0]])])`

It also ouputs a weird result if dim is 4 or 5.

**Comment by yvaucher** [comment]
Didn't had the same issue, in my case the decode wouldn't even work with an IndexError but I used more complex data than a LineString.

I attempted a patch here which seems to solve your issue: #50 

Just tested your case with it returns me 
`OrderedDict([('type', 'LineString'), ('coordinates', [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])])`

And without: OrderedDict([('type', 'LineString'), ('coordinates', [[1.0, 2.0], [4.0, 5.0], [7.0, 8.0]])])

(Didn't tried with other dimenssions.)
